name: Connect to an AWS role from a GitHub repository
on:
  push:
    branches:
      - main

env:
  AWS_REGION: "eu-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::268891750310:role/GitHub_actions_deployment
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Test connection
        run: aws sts get-caller-identity
